############################################################################################################
#                                                                                                          #
# #     #                                            #     #                                               #
# ##   ##  #    #  #####   #####   ######  #####     ##   ##  #   #   ####   #####  ######  #####   #   #  #
# # # # #  #    #  #    #  #    #  #       #    #    # # # #   # #   #         #    #       #    #   # #   #
# #  #  #  #    #  #    #  #    #  #####   #    #    #  #  #    #     ####     #    #####   #    #    #    #
# #     #  #    #  #####   #    #  #       #####     #     #    #         #    #    #       #####     #    #
# #     #  #    #  #   #   #    #  #       #   #     #     #    #    #    #    #    #       #   #     #    #
# #     #   ####   #    #  #####   ######  #    #    #     #    #     ####     #    ######  #    #    #    #
#                                                                                                          #
############################################################################################################

# The language that MurderMystery will use
# Available languages: eng
#
# English language pack by @jasonwynn10
language: eng

Bow-cost: 10 # amount of gold needed to get a single-shot bow
Gold-time: 15 # time between gold spawns/despawns in seconds
corpse: false # leave corpses after players are killed?
Show-Title: true # show titles on game start?

Games: # game settings
  "Game 1": # customizable game name
    World: "world" # what world is the game map in?
    Player-Spawn-Area: # innocent players will spawn within this area
      X1: 0
      Y1: 0
      Z1: 0
      X2: 0
      Y2: 0
      Z2: 0
    Gold-Spawn-Area: # gold will spawn within this area
      X1: 0
      Y1: 0
      Z1: 0
      X2: 0
      Y2: 0
      Z2: 0
    max-players: 7 # maximum players before others are not allowed to join
    min-players: 4 # minimum players to start